# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  
  generate_db:
    cmds:
      - cd db; sqlc generate
      - cd ../mobile/TakeBread/api; ./generate.sh
      - cd swagger; ./generate.sh

